ignore:
  - ".building"
  - ".debug"
  - ".github"
  - ".vscode"
  - ".gitattritbutes"
  - ".gitignore"
  - "LICENSE"
  - "README.md"
  - "noita-mp/files/lib"
  - "mods/noita-mp/files/lib"
  - "luarocks-3.8.0/.codecov.yml"
  - "mods"
