name: lua-testing

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["luajit-2.0.4", "5.1.5", "noitalua51.dll"]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Get Lua from cache
      uses: ./dll_building/lua-enet-master_21-10-2015_ENet1-3-17_Noita-lua51-dll/noitalua51.dll

    - name: build
      run: |
        luarocks install busted
        luarocks install luaffi
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal
