name: lua-testing

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["luajit-2.0.4", "5.1.5"]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: build
      run: |
        luarocks install luacov
        luarocks install busted
        luarocks install luaffi
        luarocks make

    - name: test
      run: |
        busted -o utfTerminal

  test2:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install lua51 and luarocks 2.0.4
      run: |
        # install lua manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        sudo apt install build-essential libreadline-dev unzip
        curl -R -O http://www.lua.org/ftp/lua-5.1.tar.gz
        tar -zxf lua-5.1.tar.gz
        cd lua-5.1
        make linux test
        sudo make install

        # install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        wget https://luarocks.github.io/luarocks/releases/luarocks-2.0.4.tar.gz
        tar zxpf luarocks-2.0.4.tar.gz
        cd luarocks-2.0.4
        ./configure --with-lua-include=/usr/local/include
        make
        sudo make install

    - name: Generate coverage report
      run: |
        # run luarocks commands
        sudo luarocks install luacov
        sudo luarocks install busted
        busted -o utfTerminal
        luacov ./spec/luacov/.luacov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./spec/luacov/luacov.report.out
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

