name: lua-testing

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install lua 5.1.5 and luarocks 2.0.4
      run: |
        ################ install lua manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        echo "> sudo apt install build-essential libreadline-dev unzip"
        sudo apt install build-essential libreadline-dev unzip
        
        echo "> curl -R -O http://www.lua.org/ftp/lua-5.1.5.tar.gz"
        curl -R -O http://www.lua.org/ftp/lua-5.1.5.tar.gz
        
        echo "> tar -zxf lua-5.1.5.tar.gz"
        tar -zxf lua-5.1.5.tar.gz
        
        echo "> cd lua-5.1.5"
        cd lua-5.1.5
        
        echo "> sudo make linux test"
        make linux test

        echo "> sudo make install INSTALL_TOP=${{ github.workspace }}/lua51"
        make install INSTALL_TOP=${{ github.workspace }}/lua51

        echo "> ls -lsa ${{ github.workspace }}/lua51"
        ls -lsa ${{ github.workspace }}/lua51

        ################ install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        echo "> wget https://luarocks.github.io/luarocks/releases/luarocks-3.8.0.tar.gz"
        wget https://luarocks.github.io/luarocks/releases/luarocks-3.8.0.tar.gz

        echo "> tar zxpf luarocks-3.8.0.tar.gz"
        tar zxpf luarocks-3.8.0.tar.gz

        echo "> cd luarocks-3.8.0"
        cd luarocks-3.8.0

        echo "> sudo ./configure --prefix=${{ github.workspace }}/luarocks --with-lua-include=${{ github.workspace }}/lua51/include --with-lua=${{ github.workspace }}/lua51"
        ./configure --prefix=${{ github.workspace }}/luarocks --with-lua-include=${{ github.workspace }}/lua51/include --with-lua=${{ github.workspace }}/lua51

        echo "> sudo make"
        make

        echo "> sudo make install"
        make install

        echo "> ls -lsa ${{ github.workspace }}/luarocks"
        ls -lsa ${{ github.workspace }}/luarocks

        echo "> ls -lsa ${{ github.workspace }}/luarocks/bin"
        ls -lsa ${{ github.workspace }}/luarocks/bin

        echo "> ls -lsa ${{ github.workspace }}/luarocks/etc"
        ls -lsa ${{ github.workspace }}/luarocks/etc

        echo "> ls -lsa ${{ github.workspace }}/luarocks/share"
        ls -lsa ${{ github.workspace }}/luarocks/share

    - name: Generate coverage report
      run: |
        ################ run luarocks commands
        echo "> sudo luarocks install luacov"
        ${{ github.workspace }}/luarocks/bin/luarocks install luacov

        echo "> sudo luarocks install busted"
        ${{ github.workspace }}/luarocks/bin/luarocks install busted

        echo "> sudo luarocks install luasystem" # https://githubmemory.com/repo/Olivine-Labs/busted/issues/650
        ${{ github.workspace }}/luarocks/bin/luarocks install luasystem


        echo "> ls -lsa ${{ github.workspace }}/luarocks"
        ls -lsa ${{ github.workspace }}/luarocks

        echo "> ls -lsa ${{ github.workspace }}/luarocks/bin"
        ls -lsa ${{ github.workspace }}/luarocks/bin

        echo "> ls -lsa ${{ github.workspace }}/luarocks/etc/luarocks"
        ls -lsa ${{ github.workspace }}/luarocks/etc/luarocks

        echo "> ls -lsa ${{ github.workspace }}/luarocks/share/lua/5.1"
        ls -lsa ${{ github.workspace }}/luarocks/share/lua/5.1

        echo "> ls -lsa ${{ github.workspace }}/luarocks/share/lua/5.1/system/init"
        ls -lsa ${{ github.workspace }}/luarocks/share/lua/5.1/system/init

        echo "> ${{ github.workspace }}/luarocks/bin/luarocks --version"
        ${{ github.workspace }}/luarocks/bin/luarocks --version

        echo "> sudo busted -o utfTerminal"
        ${{ github.workspace }}/luarocks/bin/busted -o utfTerminal

        echo "> sudo luacov ./spec/luacov/.luacov"
        ${{ github.workspace }}/luarocks/bin/luacov ./spec/luacov/.luacov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./spec/luacov/luacov.report.out
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

