name: lua-testing

on: [push, pull_request]

jobs:
  lua-unit-tests:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install luaJIT 2.0.4
      #if: ${{ false }} to disable a step
      run: |
        cd ${{ github.workspace }}/.building/LuaJIT-2.0.4
        make PREFIX=${{ github.workspace }}/luajit
        make install PREFIX=${{ github.workspace }}/luajit
        #ls -lsaR ${{ github.workspace }}/luajit

    - name: Run LuaUnit 3.4
      run: |
        ######## copy luaunit.lua to package directory, because I don't want to mess around with lua pathes again
        cp ${{ github.workspace }}/.testing/luaunit.lua ${{ github.workspace }}/luajit/share/lua/5.1/
        ######## run all lua test files with one command: https://stackoverflow.com/a/10523492/3493998
        sudo find ${{ github.workspace }}/.testing -maxdepth 1 -type f -exec ${{ github.workspace }}/luajit/bin/luajit {} -o text --verbose --failure --error \; > ${{ github.workspace }}/.testing/testresult.log

    - name: Install luarocks 3.8.0
      run: |
        ######## install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        wget https://luarocks.github.io/luarocks/releases/luarocks-3.8.0.tar.gz
        tar zxpf luarocks-3.8.0.tar.gz
        cd luarocks-3.8.0
        ######## set luajit pathes to luarocks
        ./configure --prefix=${{ github.workspace }}/luarocks --with-lua=${{ github.workspace }}/luajit --with-lua-include=${{ github.workspace }}/luajit/include/luajit-2.0 --with-lua-lib=${{ github.workspace }}/luajit/lib
        make
        make install
        #ls -lsaR ${{ github.workspace }}/luarocks

    - name: Install dependencies
      run: |
        ######## Use --tree to define the installation path of the module, which is luajit/share/lua/5.1/ although only the 'root' directory is set
        ${{ github.workspace }}/luarocks/bin/luarocks --tree=${{ github.workspace }}/luajit install luacov
        #ls -lsaR ${{ github.workspace }}/luajit/share/lua/5.1/

    - name: Generate coverage report with luacov
      run: |
        # https://leafo.net/guides/customizing-the-luarocks-tree.html#how-lua-finds-packages/setting-the-path-with-luarocks
        #echo "${{ github.workspace }}/luarocks/bin/luarocks path"
        #${{ github.workspace }}/luarocks/bin/luarocks path >> ~/.bashrc

        sudo find ${{ github.workspace }}/.testing -maxdepth 1 -type f -exec ${{ github.workspace }}/luajit/bin/luajit -lluacov {} \;

        ls -lsaR

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./spec/luacov/luacov.report.out
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

