name: lua-testing

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Install lua 5.1.5 and luarocks 2.0.4
      run: |
        ################ install lua manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        echo "> sudo apt install build-essential libreadline-dev unzip"
        sudo apt install build-essential libreadline-dev unzip
        
        echo "> curl -R -O http://www.lua.org/ftp/lua-5.1.5.tar.gz"
        curl -R -O http://www.lua.org/ftp/lua-5.1.5.tar.gz
        
        echo "> tar -zxf lua-5.1.5.tar.gz"
        tar -zxf lua-5.1.5.tar.gz
        
        echo "> cd lua-5.1.5"
        cd lua-5.1.5
        
        echo "> sudo make linux test"
        sudo make linux test

        echo "> sudo make install"
        sudo make install

        ################ install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        echo "> wget https://luarocks.github.io/luarocks/releases/luarocks-2.0.4.tar.gz"
        wget https://luarocks.github.io/luarocks/releases/luarocks-2.0.4.tar.gz

        echo "> tar zxpf luarocks-2.0.4.tar.gz"
        tar zxpf luarocks-2.0.4.tar.gz

        echo "> cd luarocks-2.0.4"
        cd luarocks-2.0.4

        echo "> sudo ./configure --with-lua-include=/usr/local/include"
        sudo ./configure --with-lua-include=/usr/local/include

        echo "> sudo make"
        sudo make

        echo "> sudo make install"
        sudo make install

    - name: Generate coverage report
      run: |
        ################ run luarocks commands
        echo "> sudo luarocks install luacov"
        sudo luarocks install luacov

        echo "> sudo luarocks install busted"
        sudo luarocks install busted

        #echo "> sudo luarocks install luasystem" # https://githubmemory.com/repo/Olivine-Labs/busted/issues/650
        #sudo luarocks install luasystem

        echo "> sudo busted -o utfTerminal"
        sudo busted -o utfTerminal

        echo "> sudo luacov ./spec/luacov/.luacov"
        sudo luacov ./spec/luacov/.luacov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./spec/luacov/luacov.report.out
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true

