name: Windows Lua Unit Testing

on: [push, pull_request]

jobs:
  lua-unit-testing-on-windows-latest:
    name: "LuaUnit on Windows-latest (mingw32)"
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main

    - name: Install luaJIT 2.0.4
      if: ${{ false }}
      run: |
        cd ${{ github.workspace }}\.building\LuaJIT-2.0.4
        ### PREFIX isn't working on windows mingw32/powershell, but I don't care. luaJIT is installed in ${{ github.workspace }}\.building\LuaJIT-2.0.4\src\luajit.exe
        mingw32-make
        mingw32-make install

    - name: Build Lua 5.1.5
      run: |
        ### https://gist.github.com/Egor-Skriptunoff/cb952f7eaf39b7b1bf739b818ece87cd
        ### http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies
        New-Item -Path "${{ github.workspace }}" -Name "temp" -ItemType "directory"
        cd ${{ github.workspace }}\temp\
        Invoke-WebRequest -Uri "https://www.lua.org/ftp/lua-5.1.5.tar.gz" -OutFile "${{ github.workspace }}\temp\lua-5.1.5.tar.gz"
        #Expand-Archive -Path "${{ github.workspace }}\temp\lua-5.1.5.tar.gz" -DestinationPath "${{ github.workspace }}\temp\lua-5.1.5\"
        tar zxpf lua-5.1.5.tar.gz
        cd ${{ github.workspace }}\temp\lua-5.1.5\
        mingw32-make PLAT=mingw
        ls -R

    - name: Build LuaJIT 2.0.4
      run: |
        ### https://gist.github.com/Egor-Skriptunoff/cb952f7eaf39b7b1bf739b818ece87cd
        ### http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies
        Copy-Item -Path "${{ github.workspace }}\.building\LuaJIT-2.0.4\" -Destination "${{ github.workspace }}\temp\LuaJIT-2.0.4\" -Recurse
        cd ${{ github.workspace }}\temp\LuaJIT-2.0.4\
        mingw32-make PLAT=mingw
        ls -R

    - name: Install Lua 5.1.5 and LuaJIT 2.0.4
      run: |
        ### https://gist.github.com/Egor-Skriptunoff/cb952f7eaf39b7b1bf739b818ece87cd
        ### http://lua-users.org/wiki/BuildingLuaInWindowsForNewbies
        New-Item -Path "${{ github.workspace }}" -Name "Lua" -ItemType "directory"
        New-Item -Path "${{ github.workspace }}\Lua" -Name "bin" -ItemType "directory"
        Copy-Item "${{ github.workspace }}\temp\lua-5.1.5\src\lua.exe" -Destination "${{ github.workspace }}\Lua\"
        Copy-Item "${{ github.workspace }}\temp\lua-5.1.5\src\luac.exe" -Destination "${{ github.workspace }}\Lua\"
        Copy-Item "${{ github.workspace }}\temp\lua-5.1.5\src\lua51.dll" -Destination "${{ github.workspace }}\Lua\"
        Copy-Item "${{ github.workspace }}\temp\LuaJIT-2.0.4\src\luajit.exe" -Destination "${{ github.workspace }}\Lua\"
        Copy-Item "${{ github.workspace }}\temp\LuaJIT-2.0.4\src\lua51.dll" -Destination "${{ github.workspace }}\Lua\"
        Copy-Item "${{ github.workspace }}\temp\LuaJIT-2.0.4\src\jit\" -Destination "${{ github.workspace }}\Lua\lua\jit\"
        ls -R ${{ github.workspace }}\Lua\

        Start-Process -FilePath "${{ github.workspace }}\Lua\lua.exe" -ArgumentList " -v" -Wait -NoNewWindow
        Start-Process -FilePath "${{ github.workspace }}\Lua\luajit.exe" -ArgumentList " -v" -Wait -NoNewWindow
        Start-Process -FilePath "${{ github.workspace }}\Lua\luajit.exe" -ArgumentList " -e `"print(_VERSION)`"" -Wait -NoNewWindow

    - name: Run LuaUnit 3.4
      id: lua_unit_tests
      run: |
        Copy-Item "${{ github.workspace }}\.testing\luaunit.lua" -Destination "${{ github.workspace }}\Lua\lua\"

        dir -Path ${{ github.workspace }}\.testing\tests -Filter *.lua -Recurse | %{& '${{ github.workspace }}\Lua\luajit.exe' $_.FullName -o text --verbose --error > ${{ github.workspace }}\.testing\testresult.log}
        type ${{ github.workspace }}\.testing\testresult.log
        
        # https://timheuer.com/blog/manually-force-a-failure-in-github-action-step/
        $testFail = Select-String -Path ${{ github.workspace }}\.testing\testresult.log -Pattern 'FAIL' -CaseSensitive
        Write-Output "::set-output name=fail::$testFail"
        
        $testError = Select-String -Path ${{ github.workspace }}\.testing\testresult.log -Pattern 'ERROR' -CaseSensitive
        Write-Output "::set-output name=error::$testError"
      
    - name: Unit test failed?
      ### Check if tests succeed:
      if: ${{ steps.lua_unit_tests.outputs.fail != '' || steps.lua_unit_tests.outputs.error != '' }}
      run: |
        echo "steps.lua_unit_tests.outputs.fail = ${{ steps.lua_unit_tests.outputs.fail }}"
        echo "steps.lua_unit_tests.outputs.error = ${{ steps.lua_unit_tests.outputs.error }}"
        echo "Unit tests failed!"
        exit 1

    - name: Install luarocks 3.8.0 windows
      run: |
        ### install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
      
        #wget https://luarocks.github.io/luarocks/releases/luarocks-3.8.0.tar.gz
        Invoke-WebRequest -Uri "http://luarocks.github.io/luarocks/releases/luarocks-3.8.0-win32.zip" -OutFile "${{ github.workspace }}\luarocks-3.8.0-win32.zip"

        #tar zxpf luarocks-3.8.0.tar.gz
        Expand-Archive -Path ${{ github.workspace }}\luarocks-3.8.0-win32.zip -DestinationPath "${{ github.workspace }}\luarocks-3.8.0-win32"

        cd luarocks-3.8.0-win32

        New-Item -Path "C:" -Name "luarocks" -ItemType "directory"
        Copy-Item "${{ github.workspace }}\.building\luarocks-3.8.0\config-windows.5.1.lua" -Destination "C:\luarocks\config.lua"

        #ls -R ${{ github.workspace }}

        ### set environment variable https://stackoverflow.com/a/1333717/3493998 + https://www.tutorialspoint.com/how-to-set-environment-variables-using-powershell
        [System.Environment]::SetEnvironmentVariable('LUAROCKS_CONFIG','${{ github.workspace }}\.building\luarocks-3.8.0\config-windows.5.1.lua')

        #dir env:

        #ls C:/

        #ls C:/luarocks

        cd ${{ github.workspace }}\luarocks-3.8.0-win32\luarocks-3.8.0-win32\

        ls ${{ github.workspace }}\luarocks-3.8.0-win32\luarocks-3.8.0-win32\install.bat

        ### set luajit pathes to luarocks
        #.\configure --prefix=${{ github.workspace }}\luarocks --with-lua=${{ github.workspace }}\luajit --with-lua-include=${{ github.workspace }}\luajit\include\luajit-2.0 --with-lua-lib=${{ github.workspace }}\luajit\lib
        Write-Host "Start-Process -FilePath "${{ github.workspace }}\luarocks-3.8.0-win32\luarocks-3.8.0-win32\install.bat" -Wait -NoNewWindow"
        Start-Process -FilePath "install.bat" -ArgumentList "/?" -Wait -NoNewWindow

        Remove-Item -Path ${{ github.workspace }}\luarocks-3.8.0-win32.zip
        Remove-Item -Path ${{ github.workspace }}\luarocks-3.8.0-win32 -Recurse

    - name: Install luarocks 3.8.0 linux
      run: |
        ######## install lua rocks manually: https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix
        wget https://luarocks.github.io/luarocks/releases/luarocks-3.8.0.tar.gz
        tar zxpf luarocks-3.8.0.tar.gz
        cd luarocks-3.8.0
        ######## set luajit pathes to luarocks
        ./configure --prefix=${{ github.workspace }}/luarocks --with-lua=${{ github.workspace }}/luajit --with-lua-include=${{ github.workspace }}/luajit/include/luajit-2.0 --with-lua-lib=${{ github.workspace }}/luajit/lib
        make
        make install

    - name: Install dependencies
      run: |
        ######## Use --tree to define the installation path of the module, which is luajit/share/lua/5.1/ although only the 'root' directory is set
        Start-Process -FilePath "${{ github.workspace }}\luarocks\bin\luarocks" -ArgumentList "/TREE=${{ github.workspace }}\.building\LuaJIT-2.0.4\src\lua\ install luacov" -Wait -NoNewWindow

    - name: Generate coverage report with luacov
      run: |
        sudo find ${{ github.workspace }}\.testing\tests -name "*.lua" -type f -exec ${{ github.workspace }}\luajit\bin\luajit -lluacov {} \;
        ${{ github.workspace }}\luajit\bin\luacov

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ${{ github.workspace }}
        #path_to_write_report: ./codecov_report.txt https://github.com/codecov/codecov-action/issues/476
        verbose: true
